# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IbooksNotesExporter < Formula
  desc ""
  homepage ""
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/57uff3r/ibooks_notes_exporter/releases/download/v0.0.1/ibooks_notes_exporter_0.0.1_Darwin_arm64.tar.gz"
      sha256 "b4c1c8dbe2283862cdb02a0e8fbbeda5dc98cf550bfa598f4e4e1ef05933ba9d"

      def install
        bin.install "ibooks_notes_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/57uff3r/ibooks_notes_exporter/releases/download/v0.0.1/ibooks_notes_exporter_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "f70553e0c81056d1aef98c65f514d813e9cdf5aae935309e9cdc8168fd9eea1e"

      def install
        bin.install "ibooks_notes_exporter"
      end
    end
  end
end
